language: node_js
node_js:
- 8.11.4
cache: npm
after_success:
- npm run coveralls
env:
  global:
    secure: TxyVD9MuDarF9BhLmLlBB6tda6wpuRViSaeGjqwaftMywGL+zF4QmD7Aj266PWNoRjdptN2fIBLDYe6UM4emec67dfdSHFncx6erLS6pxg1/oRXTWBnXj7wXc9gS+xevZZ2+AHhjxGrB2kfmOMzhjSlIkHBcJBx41zYaaHG2Pe/lx7DlW7VsxR9drPy0UiJfFugr/y4FYIBKs/o+0sylRI9ksqBiWu4jH/5HNSS6iaaM/hLanDIE9giOceR8Czv1FGvWNAexOdloTCX9+BL0VcpyGsoCooXabCMRRqbpccTBJV1Ypu9hVMQaconVXiwSRDIbZIdyTOMDZ54NnfUMKmAp7qRGQCmX2fdhiByriz9gds59z9ZShnJAGC9AlYD6A92WRffI4JOilsNprhB9VzXac9M1AiWLgUH4KozrfGHbC2JENjCFCytkLfw+jPvj1DgLRjr79fInl9K/G08WrA6bASaP6DLabTbsn8pcWMGLzujK46rx6Wec8jOd4eOXrUc5DHtcGwYhOLUjaqUL8h80Uwmm2JeHu+siPsQ4yM394RRa84//w+r0o1rBZXqPjGssPBprj2F1MBFaFL9ZPDU4moVSao1kqCOyVaqttvh22bhZKlENEf8Pg0FiH9pYY2v49FIenmvAhTfjlbMl8Gt5vzqEvEqGG4xCm1J0GpQ=
